version: '3'
services:
  mssql:
    build:
      context: ./mssql-json/
      args:
        eventuateCommonVersion: ${EVENTUATE_COMMON_VERSION?}
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Eventuate123!
      ACCEPT_EULA: Y
