version: '3'
services:
  eventuate-cdc-service:
    build: ./eventuate-cdc-service
    ports:
      - "8099:8080"
    links:
      - mysql
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      EVENTUATE_CDC_READER_MYSQLREADER1_TYPE: polling
      EVENTUATE_CDC_READER_MYSQLREADER1_DATASOURCEURL: jdbc:mysql://mysql:3306/eventuate
      EVENTUATE_CDC_READER_MYSQLREADER1_DATASOURCEUSERNAME: mysqluser
      EVENTUATE_CDC_READER_MYSQLREADER1_DATASOURCEPASSWORD: mysqlpw
      EVENTUATE_CDC_READER_MYSQLREADER1_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_MYSQLREADER1_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1
      EVENTUATE_CDC_READER_MYSQLREADER1_OUTBOXID: 1

      EVENTUATE_CDC_READER_MYSQLREADER2_TYPE: polling
      EVENTUATE_CDC_READER_MYSQLREADER2_DATASOURCEURL: jdbc:mysql://mysql:3306/eventuate
      EVENTUATE_CDC_READER_MYSQLREADER2_DATASOURCEUSERNAME: mysqluser
      EVENTUATE_CDC_READER_MYSQLREADER2_DATASOURCEPASSWORD: mysqlpw
      EVENTUATE_CDC_READER_MYSQLREADER2_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_MYSQLREADER2_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1
      EVENTUATE_CDC_READER_MYSQLREADER2_OUTBOXID: 1
      EVENTUATE_CDC_READER_MYSQLREADER2_POLLINGPARALLELCHANNELNAMES: parallel_channel_1

      EVENTUATE_CDC_PIPELINE_P1_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_P1_READER: MYSQLREADER2

      EVENTUATE_CDC_PIPELINE_P2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_P2_READER: MYSQLREADER1

      EVENTUATE_CDC_PIPELINE_P3_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_P3_READER: MYSQLREADER1

      EVENTUATE_CDC_PIPELINE_P4_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_P4_READER: MYSQLREADER2
